name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "system_files/shared/usr/share/ublue-os/just"
  push:
    branches:
      - main
    paths:
      - "Justfile"

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Just
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install just
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Check Just Syntax
        shell: bash
        run: |
          just --version
          just check
